export const DEFAULT_CATEGORIES = [
  {
    id: 'piano',
    name: 'Piano',
    slug: 'piano',
    icon: '/icons/piano.svg',
    description: 'Master classical to modern piano techniques.',
    image: '/instruments/piano.jpg',
    status: 'Active',
    isFeatured: true,
    isUpcoming: false,
    isVisible: true,
    coursesCount: 3,
    startingPrice: 3500,
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'guitar',
    name: 'Guitar',
    slug: 'guitar',
    icon: '/icons/guitar.svg',
    description: 'Learn acoustic, electric, and bass guitar.',
    image: '/instruments/guitar.jpg',
    status: 'Active',
    isFeatured: true,
    isUpcoming: false,
    isVisible: true,
    coursesCount: 3,
    startingPrice: 3500,
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'drums',
    name: 'Drums',
    slug: 'drums',
    icon: '/icons/drums.svg',
    description: 'Develop rhythm, timing, and drumming patterns.',
    image: '/instruments/drums.jpg',
    status: 'Active',
    isFeatured: false,
    isUpcoming: false,
    isVisible: true,
    coursesCount: 3,
    startingPrice: 3500,
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'vocals',
    name: 'Vocals',
    slug: 'vocals',
    icon: '/icons/microphone.svg',
    description: 'Train your voice and build confidence.',
    image: '/instruments/vocals.jpg',
    status: 'Active',
    isFeatured: false,
    isUpcoming: false,
    isVisible: true,
    coursesCount: 3,
    startingPrice: 3500,
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'violin',
    name: 'Violin',
    slug: 'violin',
    icon: '/icons/violin.svg',
    description: 'Learn bowing, posture, and beautiful classical repertoire.',
    image: '/instruments/violin.jpg',
    status: 'Active',
    isFeatured: false,
    isUpcoming: false,
    isVisible: true,
    coursesCount: 3,
    startingPrice: 3500,
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'music-theory',
    name: 'Music Theory',
    slug: 'music-theory',
    icon: '/icons/music-theory.svg',
    description: 'Understand notes, reading, notation, and harmony.',
    image: '/instruments/music-theory.jpg',
    status: 'Active',
    isFeatured: false,
    isUpcoming: false,
    isVisible: true,
    coursesCount: 3,
    startingPrice: 3500,
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'bass-guitar',
    name: 'Bass Guitar',
    slug: 'bass-guitar',
    icon: '/icons/bass-guitar.svg',
    description: 'Lay the low end foundation with proper techniques.',
    image: '/instruments/bass-guitar.jpg',
    status: 'Active',
    isFeatured: false,
    isUpcoming: false,
    isVisible: true,
    coursesCount: 3,
    startingPrice: 3500,
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'saxophone',
    name: 'Saxophone',
    slug: 'saxophone',
    icon: '/icons/saxophone.svg',
    description: 'Breathe life into jazz, blues, and classical solos.',
    image: '/instruments/saxophone.jpg',
    status: 'Upcoming',
    isFeatured: false,
    isUpcoming: true,
    isVisible: true,
    coursesCount: 0,
    startingPrice: 3500,
    levels: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const DEFAULT_COURSES = [
  // Piano Courses
  {
    id: 'piano-beginner',
    title: 'Piano Beginner',
    category: 'piano',
    level: 'Beginner',
    price: 3500,
    discountPrice: 3199,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '3 Months',
    rating: 4.8,
    students: 120,
    image: '/courses/piano-beginner.jpg',
    bannerImage: null,
    description: 'Build a strong piano foundation with posture, note reading, scales, and your first performance pieces.',
    aboutCourse: 'Learn basic keyboard layout, correct finger numbering, posture, and simple two-hand melodies.',
    curriculum: ['Fundamentals & Posture', 'Scales & Key Signatures', 'Practice Exercises', 'Performance Repertoire', 'Final Assignment'],
    learningOutcomes: ['Play basic tunes with both hands', 'Read basic sheet music', 'Understand simple rhythm divisions'],
    prerequisites: ['No prior experience required'],
    topicsCovered: ['Hand placement', 'Finger independence', 'Treble & Bass clef'],
    highlights: ['Interactive lessons', 'Professional feedback', 'Certificate of completion'],
    isDisabled: false,
    featured: true,
    upcoming: false,
    demoVideo: '',
    galleryImages: [],
    faq: [{ q: 'Do I need a piano at home?', a: 'Yes, a standard keyboard or digital piano with at least 61 keys is recommended.' }],
    lessons: 24,
    projects: 3,
    assignments: 5,
    hasCertificate: true,
    maxStudents: 30,
    difficulty: 'Easy',
    language: 'English',
    status: 'Published',
    thumbnail: null
  },
  {
    id: 'piano-intermediate',
    title: 'Piano Intermediate',
    category: 'piano',
    level: 'Intermediate',
    price: 3999,
    discountPrice: 3599,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '4 Months',
    rating: 4.8,
    students: 95,
    image: '/courses/piano-intermediate.jpg',
    bannerImage: null,
    description: 'Develop expressive playing, chord voicings, sight-reading fluency, and stylistic versatility in piano.',
    aboutCourse: 'Take your playing to the next level with dynamic variations, minor scales, and blues chord progressions.',
    curriculum: ['Advanced Scales', 'Chords & Inversions', 'Blues Progressions', 'Dynamics & Expression', 'Midterm & Final Projects'],
    learningOutcomes: ['Play in multiple key signatures', 'Execute chord inversions fluidly', 'Use sustain pedal expressively'],
    prerequisites: ['Successful completion of Beginner course or 6 months playing experience'],
    topicsCovered: ['Scale routines', 'Improvisation basics', 'Repertoire study'],
    highlights: ['Step-by-step videos', 'Weekly group check-ins', 'Certificate of completion'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    demoVideo: '',
    galleryImages: [],
    faq: [{ q: 'Is this course suitable for self-taught players?', a: 'Yes, if you already know basic scales and note reading.' }],
    lessons: 32,
    projects: 4,
    assignments: 7,
    hasCertificate: true,
    maxStudents: 25,
    difficulty: 'Medium',
    language: 'English',
    status: 'Published',
    thumbnail: null
  },
  {
    id: 'piano-advanced',
    title: 'Piano Advanced',
    category: 'piano',
    level: 'Advanced',
    price: 4500,
    discountPrice: 3999,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '6 Months',
    rating: 4.9,
    students: 65,
    image: '/courses/piano-advanced.jpg',
    bannerImage: null,
    description: 'Master advanced repertoire, improvisation, performance technique, and professional-level musicianship in piano.',
    aboutCourse: 'Delve into classical masterpieces, jazz voicings, complex syncopations, and live performance mastery.',
    curriculum: ['Melodic & Harmonic Minor Scales', 'Extended Chords & Voicings', 'Complex Rhythms & Polyrhythms', 'Improvisation & Soloing', 'Concert Preparation'],
    learningOutcomes: ['Perform professional concert repertoire', 'Improvise over complex chord progressions', 'Lead/accompany band settings'],
    prerequisites: ['Intermediate level or audition review'],
    topicsCovered: ['Sight-reading classical scores', 'Jazz harmony principles', 'Live performance techniques'],
    highlights: ['1-on-1 mentor sessions', 'Performance critique', 'TCL/ABRSM prep guidelines'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    demoVideo: '',
    galleryImages: [],
    faq: [{ q: 'Can I prepare for Trinity examinations through this?', a: 'Yes, the curriculum covers equivalent grades.' }],
    lessons: 48,
    projects: 6,
    assignments: 10,
    hasCertificate: true,
    maxStudents: 20,
    difficulty: 'Hard',
    language: 'English',
    status: 'Published',
    thumbnail: null
  },

  // Guitar Courses
  {
    id: 'guitar-beginner',
    title: 'Guitar Beginner',
    category: 'guitar',
    level: 'Beginner',
    price: 3500,
    discountPrice: 3199,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '3 Months',
    rating: 4.8,
    students: 150,
    image: '/courses/guitar-beginner.jpg',
    bannerImage: null,
    description: 'Learn open chords, basic strumming patterns, and your first acoustic songs.',
    aboutCourse: 'Perfect for absolute beginners. Learn guitar parts, tuning, open chords, and simple songs.',
    curriculum: ['Introduction to Guitar', 'Basic Chords', 'Strumming & Rhythm', 'Playing First Songs'],
    learningOutcomes: ['Tune guitar correctly', 'Play major/minor open chords', 'Strum in common time signatures'],
    prerequisites: ['No prior experience required'],
    topicsCovered: ['Tuning', 'Strumming', 'Basic Chords'],
    highlights: ['Clean video tutorials', 'Interactive chord diagrams'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 24,
    projects: 3,
    assignments: 5,
    hasCertificate: true,
    maxStudents: 30,
    difficulty: 'Easy',
    language: 'English',
    status: 'Published'
  },
  {
    id: 'guitar-intermediate',
    title: 'Guitar Intermediate',
    category: 'guitar',
    level: 'Intermediate',
    price: 3999,
    discountPrice: 3599,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '4 Months',
    rating: 4.7,
    students: 110,
    image: '/courses/guitar-intermediate.jpg',
    bannerImage: null,
    description: 'Master barre chords, scales, fingerpicking, and simple solos.',
    aboutCourse: 'Take the next step: fingerpicking, pentatonic scales, major scale shapes, and barre chords.',
    curriculum: ['Barre Chords', 'Scales & Pentatonics', 'Fingerstyle Basics', 'Improvisation'],
    learningOutcomes: ['Play barre chords without buzz', 'Solo using pentatonic scale', 'Play fingerstyle arrangements'],
    prerequisites: ['Completion of beginner course or equivalent'],
    topicsCovered: ['Barre chords', 'Lead scales', 'Fingerpicking patterns'],
    highlights: ['Backing tracks included', 'Tablatures provided'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 32,
    projects: 4,
    assignments: 7,
    hasCertificate: true,
    maxStudents: 25,
    difficulty: 'Medium',
    language: 'English',
    status: 'Published'
  },
  {
    id: 'guitar-advanced',
    title: 'Guitar Advanced',
    category: 'guitar',
    level: 'Advanced',
    price: 4500,
    discountPrice: 3999,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '6 Months',
    rating: 4.9,
    students: 70,
    image: '/courses/guitar-advanced.jpg',
    bannerImage: null,
    description: 'Explore shredding, modal theory, advanced jazz chords, and complex fingerstyle compositions.',
    aboutCourse: 'Master complex techniques like sweep picking, tapping, modal improvisation, and chord melody arrangements.',
    curriculum: ['Modal Theory', 'Speed & Dexterity', 'Advanced Improvisation', 'Performance Pieces'],
    learningOutcomes: ['Understand and apply modal scales', 'Shred with speed and accuracy', 'Compose guitar arrangements'],
    prerequisites: ['Audition review or equivalent intermediate skill'],
    topicsCovered: ['Sweep picking', 'Jazz harmony', 'Modal theory'],
    highlights: ['Masterclass access', 'Solo recording project'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 48,
    projects: 6,
    assignments: 10,
    hasCertificate: true,
    maxStudents: 20,
    difficulty: 'Hard',
    language: 'English',
    status: 'Published'
  },

  // Drums Courses
  {
    id: 'drums-beginner',
    title: 'Drums Beginner',
    category: 'drums',
    level: 'Beginner',
    price: 3500,
    discountPrice: 3199,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '3 Months',
    rating: 4.8,
    students: 90,
    image: '/courses/drums-beginner.jpg',
    bannerImage: null,
    description: 'Learn basic drum grip, fundamental rudiments, and core rock beats.',
    aboutCourse: 'Get started on the drums. Learn grip, standard notation, primary rudiments, and rock beats.',
    curriculum: ['Sticks & Grip', 'Rudiments 101', 'Basic Rock Beats', 'Timing & Practice'],
    learningOutcomes: ['Proper stick holding', 'Play basic rudiments', 'Play a solid rock groove'],
    prerequisites: ['No prior experience required'],
    topicsCovered: ['Rudiments', 'Standard 4/4 beats', 'Drum kit parts'],
    highlights: ['Practice pad exercises', 'Timing metronome tracks'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 24,
    projects: 3,
    assignments: 5,
    hasCertificate: true,
    maxStudents: 30,
    difficulty: 'Easy',
    language: 'English',
    status: 'Published'
  },
  {
    id: 'drums-intermediate',
    title: 'Drums Intermediate',
    category: 'drums',
    level: 'Intermediate',
    price: 4000,
    discountPrice: 3600,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '4 Months',
    rating: 4.8,
    students: 60,
    image: '/courses/drums-intermediate.jpg',
    bannerImage: null,
    description: 'Explore syncopated grooves, fills, double bass techniques, and various genres.',
    aboutCourse: 'Broaden your drumming vocabulary with syncopation, drum fills, Latin beats, and double bass basics.',
    curriculum: ['Syncopation', 'Creative Drum Fills', 'Genre Studies', 'Double Bass Basics'],
    learningOutcomes: ['Coordinate complex fills', 'Play Latin & Jazz beats', 'Keep timing in odd signatures'],
    prerequisites: ['Completion of beginner course or equivalent'],
    topicsCovered: ['Drum fills', 'Funk & Jazz patterns', 'Independence drills'],
    highlights: ['Multi-angle camera tutorials', 'Play-along tracks'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 32,
    projects: 4,
    assignments: 7,
    hasCertificate: true,
    maxStudents: 25,
    difficulty: 'Medium',
    language: 'English',
    status: 'Published'
  },
  {
    id: 'drums-advanced',
    title: 'Drums Advanced',
    category: 'drums',
    level: 'Advanced',
    price: 4500,
    discountPrice: 3999,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '6 Months',
    rating: 4.9,
    students: 40,
    image: '/courses/drums-advanced.jpg',
    bannerImage: null,
    description: 'Master polyrhythms, advanced independence, linear drumming, and solo concepts.',
    aboutCourse: 'Achieve total drum kit freedom: polyrhythms, metric modulations, linear phrasing, and solo composition.',
    curriculum: ['Polyrhythms', 'Linear Phrasing', 'Advanced Solos', 'Metric Modulation'],
    learningOutcomes: ['Play polyrhythmic structures', 'Incorporate linear beats', 'Deliver professional drum solos'],
    prerequisites: ['Audition review or equivalent intermediate skills'],
    topicsCovered: ['Polyrhythms', 'Linear drumming', 'Solo concepts'],
    highlights: ['Advanced play-alongs', '1-on-1 technique assessment'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 48,
    projects: 6,
    assignments: 10,
    hasCertificate: true,
    maxStudents: 20,
    difficulty: 'Hard',
    language: 'English',
    status: 'Published'
  },

  // Vocals Courses
  {
    id: 'vocals-beginner',
    title: 'Vocals Beginner',
    category: 'vocals',
    level: 'Beginner',
    price: 3500,
    discountPrice: 3199,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '3 Months',
    rating: 4.8,
    students: 110,
    image: '/courses/vocals-beginner.jpg',
    bannerImage: null,
    description: 'Discover your vocal range, learn proper breathing techniques, and practice pitch control.',
    aboutCourse: 'Start your singing journey: posture, breath support, pitch matches, and basic vocal safety.',
    curriculum: ['Breath Control', 'Pitch Matching', 'Vocal Health', 'Basic Song Performance'],
    learningOutcomes: ['Maintain pitch accuracy', 'Apply diaphragmatic breathing', 'Sing without straining'],
    prerequisites: ['No prior experience required'],
    topicsCovered: ['Posture', 'Vowels', 'Pitch exercises'],
    highlights: ['Warm-up MP3s included', 'Vocal range evaluation'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 24,
    projects: 3,
    assignments: 5,
    hasCertificate: true,
    maxStudents: 30,
    difficulty: 'Easy',
    language: 'English',
    status: 'Published'
  },
  {
    id: 'vocals-intermediate',
    title: 'Vocals Intermediate',
    category: 'vocals',
    level: 'Intermediate',
    price: 4000,
    discountPrice: 3600,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '4 Months',
    rating: 4.7,
    students: 80,
    image: '/courses/vocals-intermediate.jpg',
    bannerImage: null,
    description: 'Expand your range, explore registers (chest, head, mix), and learn basic runs.',
    aboutCourse: 'Bridge your chest and head voice, master mixed register, and inject dynamics and phrasing.',
    curriculum: ['Chest & Head Voice', 'Vocal Register Blending', 'Dynamics & Phrasing', 'Intro to Runs'],
    learningOutcomes: ['Smoothly transition registers', 'Sing dynamic phrases', 'Add subtle vibrato'],
    prerequisites: ['Vocals Beginner or pitch match capability'],
    topicsCovered: ['Register transitions', 'Vocal runs', 'Interpretation'],
    highlights: ['Custom workout tracks', 'Vocal health tips'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 32,
    projects: 4,
    assignments: 7,
    hasCertificate: true,
    maxStudents: 25,
    difficulty: 'Medium',
    language: 'English',
    status: 'Published'
  },
  {
    id: 'vocals-advanced',
    title: 'Vocals Advanced',
    category: 'vocals',
    level: 'Advanced',
    price: 4500,
    discountPrice: 3999,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '6 Months',
    rating: 4.9,
    students: 50,
    image: '/courses/vocals-advanced.jpg',
    bannerImage: null,
    description: 'Master advanced riffs and runs, microphone techniques, and stage performance.',
    aboutCourse: 'Ultimate vocal control: complex melisma, high belts, microphone control, and live gig readiness.',
    curriculum: ['Complex Riffs & Runs', 'High Belting Safety', 'Microphone Technique', 'Performance Mastery'],
    learningOutcomes: ['Execute rapid riffs safely', 'Deliver high-impact belts', 'Command stage presence'],
    prerequisites: ['Audition review or equivalent intermediate capabilities'],
    topicsCovered: ['High belting', 'Melisma', 'Microphone safety'],
    highlights: ['Microphone feedback sessions', 'Final virtual concert project'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 48,
    projects: 6,
    assignments: 10,
    hasCertificate: true,
    maxStudents: 20,
    difficulty: 'Hard',
    language: 'English',
    status: 'Published'
  },

  // Violin Courses
  {
    id: 'violin-beginner',
    title: 'Violin Beginner',
    category: 'violin',
    level: 'Beginner',
    price: 3500,
    discountPrice: 3199,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '3 Months',
    rating: 4.8,
    students: 70,
    image: '/courses/violin-beginner.jpg',
    bannerImage: null,
    description: 'Learn correct violin posture, bowing techniques, and basic folk songs.',
    aboutCourse: 'Begin your violin journey: posture, bow hold, finger placements, and beautiful folk songs.',
    curriculum: ['Holding the Violin', 'Bowing Basics', 'Finger Placements', 'First Melodies'],
    learningOutcomes: ['Hold violin and bow correctly', 'Perform clean open bow strokes', 'Play simple melodies'],
    prerequisites: ['No prior experience required'],
    topicsCovered: ['Bow grip', 'Left hand frame', 'Posture'],
    highlights: ['Bowing feedback videos', 'Note reading guide'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 24,
    projects: 3,
    assignments: 5,
    hasCertificate: true,
    maxStudents: 30,
    difficulty: 'Easy',
    language: 'English',
    status: 'Published'
  },
  {
    id: 'violin-intermediate',
    title: 'Violin Intermediate',
    category: 'violin',
    level: 'Intermediate',
    price: 4000,
    discountPrice: 3600,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '4 Months',
    rating: 4.8,
    students: 45,
    image: '/courses/violin-intermediate.jpg',
    bannerImage: null,
    description: 'Learn shifting positions (3rd position), vibrato, and classical repertoire.',
    aboutCourse: 'Take the next step in string playing: vibrato introduction, shifting to 3rd position, and classical works.',
    curriculum: ['Vibrato Introduction', 'Shifting to 3rd Position', 'Double Stops', 'Repertoire Study'],
    learningOutcomes: ['Produce warm vibrato', 'Shift to 3rd position reliably', 'Perform intermediate classical works'],
    prerequisites: ['Violin Beginner or 1 year playing experience'],
    topicsCovered: ['Vibrato', '3rd position', 'Intonation studies'],
    highlights: ['Vibrato slow-motion guides', 'Accompaniment tracks'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 32,
    projects: 4,
    assignments: 7,
    hasCertificate: true,
    maxStudents: 25,
    difficulty: 'Medium',
    language: 'English',
    status: 'Published'
  },
  {
    id: 'violin-advanced',
    title: 'Violin Advanced',
    category: 'violin',
    level: 'Advanced',
    price: 4500,
    discountPrice: 3999,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '6 Months',
    rating: 4.9,
    students: 30,
    image: '/courses/violin-advanced.jpg',
    bannerImage: null,
    description: 'Master advanced bowing styles, high position shifting, and concerto movements.',
    aboutCourse: 'Master concertos, complex bowing styles (spiccato, ricochet), and high shifts (up to 7th position).',
    curriculum: ['Spiccato & Bow Strokes', 'High Position Shifting', 'Chamber Works', 'Concerto Movements'],
    learningOutcomes: ['Execute advanced bow styles', 'Shift fluently in high registers', 'Deliver virtuosic solos'],
    prerequisites: ['Audition review or equivalent intermediate skills'],
    topicsCovered: ['Advanced bow techniques', 'High registers', 'Concerto study'],
    highlights: ['Trinity Grade 8 support', 'Masterclass reviews'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 48,
    projects: 6,
    assignments: 10,
    hasCertificate: true,
    maxStudents: 20,
    difficulty: 'Hard',
    language: 'English',
    status: 'Published'
  },

  // Music Theory Courses
  {
    id: 'music-theory-beginner',
    title: 'Music Theory Beginner',
    category: 'music-theory',
    level: 'Beginner',
    price: 3500,
    discountPrice: 3199,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '3 Months',
    rating: 4.8,
    students: 80,
    image: '/courses/music-theory-beginner.jpg',
    bannerImage: null,
    description: 'Understand staff notation, note values, major scales, and simple key signatures.',
    aboutCourse: 'Learn to read and write music: staff lines, bass/treble clefs, note values, and major scales.',
    curriculum: ['Clefs & Staff Lines', 'Rhythm & Note Values', 'Major Scale Construction', 'Basic Key Signatures'],
    learningOutcomes: ['Read treble and bass clefs', 'Identify note durations', 'Build major scales'],
    prerequisites: ['No prior experience required'],
    topicsCovered: ['Music alphabet', 'Basic note values', 'Clefs'],
    highlights: ['Interactive quizzes', 'Printable staff worksheets'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 24,
    projects: 3,
    assignments: 5,
    hasCertificate: true,
    maxStudents: 30,
    difficulty: 'Easy',
    language: 'English',
    status: 'Published'
  },
  {
    id: 'music-theory-intermediate',
    title: 'Music Theory Intermediate',
    category: 'music-theory',
    level: 'Intermediate',
    price: 4000,
    discountPrice: 3600,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '4 Months',
    rating: 4.8,
    students: 55,
    image: '/courses/music-theory-intermediate.jpg',
    bannerImage: null,
    description: 'Understand minor keys, circle of fifths, intervals, and primary triad chords.',
    aboutCourse: 'Advance your harmony: minor scales (harmonic/melodic), circles of fifths, intervals, and triads.',
    curriculum: ['Minor Keys & Scales', 'Circle of Fifths', 'Intervals Identification', 'Triad Chords'],
    learningOutcomes: ['Construct minor scale variants', 'Identify intervals quickly', 'Form and invert triads'],
    prerequisites: ['Music Theory Beginner or basic note reading ability'],
    topicsCovered: ['Intervals', 'Inversions', 'Circle of Fifths'],
    highlights: ['Harmony analysis exercises', 'Triad builder interactive app'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 32,
    projects: 4,
    assignments: 7,
    hasCertificate: true,
    maxStudents: 25,
    difficulty: 'Medium',
    language: 'English',
    status: 'Published'
  },
  {
    id: 'music-theory-advanced',
    title: 'Music Theory Advanced',
    category: 'music-theory',
    level: 'Advanced',
    price: 4500,
    discountPrice: 3999,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '6 Months',
    rating: 4.9,
    students: 35,
    image: '/courses/music-theory-advanced.jpg',
    bannerImage: null,
    description: 'Understand modes, secondary dominants, complex chord progressions, and basic composition.',
    aboutCourse: 'Master music analysis: scales modes, chromatic harmony, secondary dominants, and 4-part writing.',
    curriculum: ['Modes of Major Scale', 'Secondary Dominants', '4-Part Voice Leading', 'Analysis & Composition'],
    learningOutcomes: ['Analyze complex score sheets', 'Apply secondary dominants in songwriting', 'Write basic 4-part harmony'],
    prerequisites: ['Audition review or intermediate theory certification'],
    topicsCovered: ['Modes', 'Voice leading', 'Chromatic harmony'],
    highlights: ['Composition peer reviews', 'Analysis of classical scores'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 48,
    projects: 6,
    assignments: 10,
    hasCertificate: true,
    maxStudents: 20,
    difficulty: 'Hard',
    language: 'English',
    status: 'Published'
  },

  // Bass Guitar Courses
  {
    id: 'bass-guitar-beginner',
    title: 'Bass Guitar Beginner',
    category: 'bass-guitar',
    level: 'Beginner',
    price: 3500,
    discountPrice: 3199,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '3 Months',
    rating: 4.8,
    students: 65,
    image: '/courses/bass-guitar-beginner.jpg',
    bannerImage: null,
    description: 'Learn fingerstyle plucking, basic fretboard notes, and simple basslines.',
    aboutCourse: 'Kickstart your bass playing: fingerstyle technique, basic scales, root note playing, and lock-in beats.',
    curriculum: ['Fingerstyle Plucking', 'Fretboard Notes Mapping', 'Root-Fifth Basslines', 'Rhythmic Lock-In'],
    learningOutcomes: ['Fret and pluck cleanly', 'Map key notes on neck', 'Play root-fifth basslines'],
    prerequisites: ['No prior experience required'],
    topicsCovered: ['Plucking grip', 'Neck navigation', 'Basic timing'],
    highlights: ['Drum-loop play-alongs', 'Tuning tutorials'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 24,
    projects: 3,
    assignments: 5,
    hasCertificate: true,
    maxStudents: 30,
    difficulty: 'Easy',
    language: 'English',
    status: 'Published'
  },
  {
    id: 'bass-guitar-intermediate',
    title: 'Bass Guitar Intermediate',
    category: 'bass-guitar',
    level: 'Intermediate',
    price: 4000,
    discountPrice: 3600,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '4 Months',
    rating: 4.8,
    students: 40,
    image: '/courses/bass-guitar-intermediate.jpg',
    bannerImage: null,
    description: 'Explore slap bass, walking basslines, pentatonic scales, and genre studies.',
    aboutCourse: 'Upgrade your low end: slap & pop technique, chord tones, and walking lines for jazz and blues.',
    curriculum: ['Slap & Pop Basics', 'Chord Tones & Arpeggios', 'Walking Basslines', 'Funk Grooves'],
    learningOutcomes: ['Slap and pop basic patterns', 'Walk basslines fluidly', 'Lock with drummer fills'],
    prerequisites: ['Bass Guitar Beginner or basic fingerstyle competency'],
    topicsCovered: ['Slap bass', 'Walking lines', 'Arpeggios'],
    highlights: ['Multi-track jams', 'Interactive scale neck maps'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 32,
    projects: 4,
    assignments: 7,
    hasCertificate: true,
    maxStudents: 25,
    difficulty: 'Medium',
    language: 'English',
    status: 'Published'
  },
  {
    id: 'bass-guitar-advanced',
    title: 'Bass Guitar Advanced',
    category: 'bass-guitar',
    level: 'Advanced',
    price: 4500,
    discountPrice: 3999,
    instructor: 'Ajinkya Amrule',
    instructorId: 'instructor-1',
    duration: '6 Months',
    rating: 4.9,
    students: 25,
    image: '/courses/bass-guitar-advanced.jpg',
    bannerImage: null,
    description: 'Master advanced slap techniques, tap bass, solo concepts, and complex modal theory.',
    aboutCourse: 'Master bass soloing, double thumb slap, high range tapping, and polyrhythmic grooves.',
    curriculum: ['Double Thumb Slap', 'Two-Hand Tapping', 'Solo Composition', 'Modal Bass Grooves'],
    learningOutcomes: ['Double thumb with precision', 'Perform complex tap arrangements', 'Deliver creative bass solos'],
    prerequisites: ['Audition review or equivalent intermediate skills'],
    topicsCovered: ['Slap techniques', 'Two-hand tapping', 'Soloing'],
    highlights: ['Advanced technique audits', 'Professional feedback sessions'],
    isDisabled: false,
    featured: false,
    upcoming: false,
    lessons: 48,
    projects: 6,
    assignments: 10,
    hasCertificate: true,
    maxStudents: 20,
    difficulty: 'Hard',
    language: 'English',
    status: 'Published'
  }
];
